
# User.create(name:'admin', password:'12345678',password_confirmation:'12345678',email:'admin@admin.com',profile:'Admin account', icon:'12345678',ticket:10, admin:1)

country = Area.create(name:"オーストラリア",description:"",limit:"なし",term:"通年")
country.children.create([{name:"シドニー",description:""},{name:"メルボルン",description:"ブリスベン"},{name:"パース",description:""},{name:"アデレード",description:""},{name:"ゴールドコースト",description:""},{name:"キャンベラ",description:""}])
country = Area.create(name:"ニュージーランド",description:"",limit:"なし",term:"通年")
country.children.create([{name:"オークランド",description:""},{name:"ウェリントン",description:""},{name:"クライストチャーチ",description:""},{name:"クイーンズタウン",description:""}])
country = Area.create(name:"カナダ",description:"",limit:"6,500人",term:"通年")
country.children.create([{name:"トロント",description:""},{name:"バンクーバー",description:""},{name:"モントリオール",description:""},{name:"カルガリー",description:""}])
country = Area.create(name:"イギリス",description:"",limit:"1,000人",term:"1月,7月")
country.children.create([{name:"ロンドン",description:""},{name:"ブライトン",description:""},{name:"マンチェスター",description:""},{name:"ケンブリッジ",description:""}])
country = Area.create(name:"アイルランド",description:"",limit:"400人",term:"1月,7月")
country.children.create([{name:"ダブリン",description:""},{name:"コーク",description:""},{name:"ゴールウェイ",description:""}])
country = Area.create(name:"フランス",description:"",limit:"1,500人",term:"通年")
country.children.create([{name:"パリ",description:""},{name:"リヨン",description:""},{name:"マルセイユ",description:""}])
country = Area.create(name:"スペイン",description:"",limit:"500人",term:"通年")
country.children.create([{name:"バルセロナ",description:""},{name:"マドリード",description:""},{name:"バレンシア",description:""}])
country = Area.create(name:"ドイツ",description:"",limit:"なし",term:"通年")
country.children.create([{name:"ベルリン",description:""},{name:"ミュンヘン",description:""},{name:"フランクフルト",description:""}])
country = Area.create(name:"オーストリア",description:"",limit:"200人",term:"通年")
country.children.create([{name:"ウィーン",description:""}])
country = Area.create(name:"スロバキア",description:"",limit:"400人",term:"通年")
country.children.create([{name:"",description:""}])
country = Area.create(name:"デンマーク",description:"",limit:"なし",term:"通年")
country.children.create([{name:"コペンハーゲン",description:""}])
country = Area.create(name:"ノルウェー",description:"",limit:"なし",term:"通年")
country.children.create([{name:"オスロ",description:""}])
country = Area.create(name:"ハンガリー",description:"",limit:"200人",term:"未確定")
country.children.create([{name:"ブダペスト",description:""}])
country = Area.create(name:"ポルトガル",description:"",limit:"なし",term:"通年")
country.children.create([{name:"リスボン",description:""}])
country = Area.create(name:"チェコ",description:"",limit:"400人",term:"未確定")
country.children.create([{name:"プラハ",description:""}])
country = Area.create(name:"アイスランド",description:"",limit:"30人",term:"未確定")
country.children.create([{name:"",description:""}])
country = Area.create(name:"リトアニア",description:"",limit:"100人",term:"未確定")
country.children.create([{name:"",description:""}])
country = Area.create(name:"韓国",description:"",limit:"10,000人",term:"通年")
country.children.create([{name:"ソウル",description:""},{name:"プサン",description:""}])
country = Area.create(name:"台湾",description:"",limit:"5,000人",term:"通年")
country.children.create([{name:"台北",description:""},{name:"台中",description:""},{name:"高雄",description:""}])
country = Area.create(name:"香港",description:"",limit:"1,500人",term:"通年")
country.children.create([{name:"香港",description:""}])
country = Area.create(name:"アルゼンチン",description:"",limit:"200人",term:"通年")
country.children.create([{name:"",description:""}])
country = Area.create(name:"チリ",description:"",limit:"200人",term:"未確定")
country.children.create([{name:"",description:""}])
country = Area.create(name:"スウェーデン",description:"",limit:"未確定",term:"未確定")
country.children.create([{name:"ストックホルム",description:""}])