
# User.create(name:'admin', password:'12345678',password_confirmation:'12345678',email:'admin@admin.com',profile:'Admin account', icon:'12345678',ticket:10, admin:1)

country = Area.create(name:"オーストラリア",text:"",limit:"なし",term:"通年")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"ニュージーランド",text:"",limit:"なし",term:"通年")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"カナダ",text:"",limit:"6,500人",term:"通年")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"イギリス",text:"",limit:"1,000人",term:"1月,7月")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"アイルランド",text:"",limit:"400人",term:"1月,7月")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"フランス",text:"",limit:"1,500人",term:"通年")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"スペイン",text:"",limit:"500人",term:"通年")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"ドイツ",text:"",limit:"なし",term:"通年")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"オーストリア",text:"",limit:"200人",term:"通年")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"スロバキア",text:"",limit:"400人",term:"通年")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"デンマーク",text:"",limit:"なし",term:"通年")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"ノルウェー",text:"",limit:"なし",term:"通年")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"ハンガリー",text:"",limit:"200人",term:"未確定")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"ポーランド",text:"",limit:"500人",term:"通年")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"ポルトガル",text:"",limit:"なし",term:"通年")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"チェコ",text:"",limit:"400人",term:"未確定")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"アイスランド",text:"",limit:"30人",term:"未確定")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"リトアニア",text:"",limit:"100人",term:"未確定")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"韓国",text:"",limit:"10,000人",term:"通年")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"台湾",text:"",limit:"5,000人",term:"通年")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"香港",text:"",limit:"1,500人",term:"通年")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"アルゼンチン",text:"",limit:"200人",term:"通年")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"チリ",text:"",limit:"200人",term:"未確定")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])
country = Area.create(name:"スウェーデン",text:"",limit:"未確定",term:"未確定")
country.children.create([{name:"",text:""},{name:"",text:""},{name:"",text:""},{name:"",text:""},])